[workspace]
resolver = "2"

members = [
    "crates/eir-core",
    "tools/eir-generator",
    "tools/eir-debug",
    "apps/playground",
    "apps/admin",
]

default-members = [
    "apps/playground",
]

[workspace.dependencies]
chrono = "0.4.45"
rkyv = { version = "0.8.17", features = ["bytecheck"] }
anyhow = "1.0.104"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
roaring = "0.11.4"
