[package]
name = "eir-cli"
version = "0.0.0"
edition = "2024"

[dependencies]
rkyv = { workspace = true }
bytecheck = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
tempfile = { workspace = true }
predicates = "3.1.4"
assert_cmd = "2.2.2"

eir-core = { path = "../eir-core" }
eir-version = { path = "../eir-version" }

[[bin]]
name = "eir"
path = "src/main.rs"
